# Generated by Django 2.2.6 on 2020-08-13 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='products.Brand'),
            preserve_default=False,
        ),
    ]
