# Generated by Django 2.2.6 on 2020-08-22 19:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200822_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
